name: Frontend Pipeline

on:
  push:
    branches: [ "master" ]
    paths:
      - 'frontend/src/**'
      - 'frontend/package.json'
      - 'frontend/package-lock.json'
      - 'frontend/vite.config.ts'
      - 'frontend/tsconfig*.json'
      - 'frontend/eslint*'
      - '.github/workflows/**' 
  pull_request:
    branches: [ "master" ]
    paths:
      - 'frontend/src/**'
      - 'frontend/package.json'
      - 'frontend/package-lock.json'
      - 'frontend/vite.config.ts'
      - 'frontend/tsconfig*.json'
      - 'frontend/eslint*'
      - '.github/workflows/**' 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-frontend:
    name: Test React (Vitest)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js & NPM
        uses: ./.github/actions/setup-node-npm

      - name: Run frontend tests
        run: npm run test