name: Frontend Pipeline

on:
  push:
    branches: [ "master" ]
    paths:
      - 'frontend/src/**'
      - 'frontend/package.json'
      - 'frontend/package-lock.json'
      - 'frontend/vite.config.ts'
      - 'frontend/tsconfig*.json'
      - 'frontend/eslint*'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/src/**'
      - 'frontend/package.json'
      - 'frontend/package-lock.json'
      - 'frontend/vite.config.ts'
      - 'frontend/tsconfig*.json'
      - 'frontend/eslint*'
      - '.github/workflows/**' 
jobs:
  test-frontend:
    name: Test React (Vitest)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # This step natively caches the global ~/.npm folder
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.14.0'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run frontend tests
        run: npm run test